In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("../data/cleaned_food_delivery_data.csv")
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin,Profit_Margin_Percentage,Delivery_Performance,Customer_Age_Group,Day_of_Week
0,ORD000001,CUST6948,19.0,Male,Unknown,Central,RES936,Restaurant_29,Chinese,2024-10-20,...,DP563,5.0,4.4,Weekend,Peak Hour,0.13,13.0,Slow,Young Adult,Sunday
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12,...,DP369,5.0,4.7,Weekday,Peak Hour,0.48,48.0,Fast,Middle Age,Monday
2,ORD000003,CUST1765,39.0,Male,Delhi,Unknown,RES723,Restaurant_244,Arabian,2024-12-08,...,DP580,4.0,4.9,Weekend,Peak Hour,0.08,8.0,Slow,Middle Age,Sunday
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08,...,DP155,NaN,3.4,Weekday,Unknown,0.04,4.0,Moderate,Middle Age,Tuesday
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04,...,DP728,2.0,4.4,Weekend,Non-Peak Hour,0.12,12.0,Fast,Senior,Sunday

In [3]:
# Profit margin percentage

df["Profit_Margin"].head(10)

0    0.13
1    0.48
2    0.08
3    0.04
4    0.12
5    0.24
6    0.02
7    0.18
8    0.08
9    0.03
Name: Profit_Margin, dtype: float64

In [4]:
df["Profit_Margin_Percentage"] = df["Profit_Margin"] * 100

In [5]:
df[["Profit_Margin", "Profit_Margin_Percentage"]].head(10)

   Profit_Margin  Profit_Margin_Percentage
0           0.13                      13.0
1           0.48                      48.0
2           0.08                       8.0
3           0.04                       4.0
4           0.12                      12.0
5           0.24                      24.0
6           0.02                       2.0
7           0.18                      18.0
8           0.08                       8.0
9           0.03                       3.0

In [6]:
# Delivery performance categories

def delivery_category(time):
    if time <= 58:
        return "Fast"
    elif time <= 165:
        return "Moderate"
    else:
        return "Slow"

df["Delivery_Performance"] = df["Delivery_Time_Min"].apply(delivery_category)

In [7]:
df["Delivery_Performance"].value_counts()

Delivery_Performance
Moderate    49828
Fast        25323
Slow        24849
Name: count, dtype: int64

In [8]:
# Customer age groups
def age_group(age):
    if age <= 25:
        return "Young Adult"
    elif age <= 35:
        return "Adult"
    elif age <= 50:
        return "Middle Age"
    else:
        return "Senior"
df["Customer_Age_Group"] = df["Customer_Age"].apply(age_group)

In [9]:
df["Customer_Age_Group"].value_counts()

Customer_Age_Group
Middle Age     67609
Adult          11653
Senior         11492
Young Adult     9246
Name: count, dtype: int64

In [14]:
#creating the actual day of the week from Order_Date
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Day_of_Week"] = df["Order_Date"].dt.day_name()

In [15]:
df["Day_of_Week"].value_counts()

Day_of_Week
Monday       14401
Saturday     14322
Wednesday    14082
Thursday     14081
Friday       14069
Sunday       14046
Tuesday      13985
Name: count, dtype: int64

In [16]:
df.shape

(100000, 28)

In [17]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Delivery_Time_Min', 'Distance_km', 'Order_Value',
       'Discount_Applied', 'Final_Amount', 'Payment_Mode', 'Order_Status',
       'Cancellation_Reason', 'Delivery_Partner_ID', 'Delivery_Rating',
       'Restaurant_Rating', 'Order_Day', 'Peak_Hour', 'Profit_Margin',
       'Profit_Margin_Percentage', 'Delivery_Performance',
       'Customer_Age_Group', 'Day_of_Week'],
      dtype='object')